from django.urls import path
from . import views

urlpatterns = [
    path('api/bootstrap/', views.api_bootstrap, name='api-bootstrap'),
    path('api/home/', views.api_home, name='api-home'),
    path('api/login/', views.api_login, name='api-login'),
    path('api/logout/', views.api_logout, name='api-logout'),
    path('api/register/', views.api_register, name='api-register'),
    path('api/topics/', views.api_topic_create, name='api-topic-create'),
    path('api/rooms/form/', views.api_room_form_data, name='api-room-form-create'),
    path('api/rooms/', views.api_room_create, name='api-room-create'),
    path('api/rooms/<int:pk>/', views.api_room_detail, name='api-room-detail'),
    path('api/rooms/<int:pk>/form/', views.api_room_form_data, name='api-room-form-detail'),
    path('api/rooms/<int:pk>/update/', views.api_room_update, name='api-room-update'),
    path('api/rooms/<int:pk>/delete/', views.api_room_delete, name='api-room-delete'),
    path('api/rooms/<int:pk>/messages/', views.api_message_create, name='api-message-create'),
    path('api/messages/<int:pk>/update/', views.api_message_update, name='api-message-update'),
    path('api/messages/<int:pk>/delete/', views.api_message_delete, name='api-message-delete'),
    path('api/profile/<int:pk>/', views.api_profile_detail, name='api-profile-detail'),
    path('api/profile/<int:pk>/update/', views.api_profile_update, name='api-profile-update'),
    path('api/profile/edit/', views.api_profile_edit_data, name='api-profile-edit'),
    path('', views.app_shell, name='home'),
    path('login/', views.app_shell, name='login'),
    path('logout/', views.app_shell, name='logout'),
    path('register/', views.app_shell, name='register'),
    path('room/<int:pk>/', views.app_shell, name='room'),
    path('profile/<int:pk>/', views.app_shell, name='user-profile'),
    path('settings/profile/', views.app_shell, name='edit-profile'),
    path('create-room/', views.app_shell, name='create-room'),
    path('create-topic/', views.app_shell, name='create-topic'),
    path('update-room/<int:pk>/', views.app_shell, name='update-room'),
    path('delete-room/<int:pk>/', views.app_shell, name='delete-room'),
    path('delete-message/<int:pk>/', views.app_shell, name='delete-message'),
    path('update-message/<int:pk>/', views.app_shell, name='update-message'),
]
